### ISSUE TITLE
Install jq

### ISSUE THREAD

**Issue by mifisignal** [bottlerocket-os/bottlerocket-control-container#6]
In order for maintenance scripts to be able to parse the output of `apiclient`, it would be useful to install `jq` to provide for easy field extraction.

See https://github.com/bottlerocket-os/bottlerocket/issues/1165 for additional details.

**Comment by tjkirch** [comment]
I agree that it's worth considering having jq by default.  Just as a note, you can install jq in the control container using SSM like this:

```sh
aws ssm send-command \
        --instance-ids "MY-INSTANCE-ID" \
        --document-name "AWS-RunShellScript" \
        --parameters "{\"commands\":[\"yum -y install jq\"]}"
```

Or in the admin container with a simpler `sudo yum -y install jq`.

**Comment by tjkirch** [comment]
As mentioned in #1165, we believe we've addressed the need to parse apiclient output by adding higher-level usage modes to apiclient, so the automation around it shouldn't be needed.  There's not necessarily anything wrong with adding jq to the control container, but we'd prefer to more directly address (remove) the need for scripting around the tools, and use GitHub issues to represent any use cases that are missing.
